# Generated by Django 4.2.16 on 2024-10-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=20, null=True)),
                ("symbol", models.CharField(max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("url", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "default_base_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                ("rate_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="MyCurrencyApp.currencyprovider",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_currency",
                        to="MyCurrencyApp.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_currency",
                        to="MyCurrencyApp.currency",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "source_currency",
                        "target_currency",
                        "valuation_date",
                        "rate_value",
                    )
                },
            },
        ),
    ]
